DDCE-5225
hmrc/register-estate-hub-frontend pull request #116
Opened 2024-05-17 10:07 UTC by MRBeresford

2024-05-20 15:13 UTC, frikit requested changes

2024-05-21 09:04 UTC, MRBeresford commented on build.sbt
>    .enablePlugins(PlayScala, SbtDistributablesPlugin, SbtSassify)
removed

2024-05-21 09:04 UTC, MRBeresford commented on build.sbt
>      DefaultBuildSettings.scalaSettings,
removed and removed import

2024-05-21 09:04 UTC, MRBeresford commented on build.sbt
>      DefaultBuildSettings.defaultSettings(),
removed and removed import

2024-05-21 09:04 UTC, MRBeresford commented on build.sbt
>      TwirlKeys.templateImports ++= Seq(
added

2024-05-21 09:04 UTC, MRBeresford commented on project/AppDependencies.scala
>      "com.vladsch.flexmark"        %  "flexmark-all"             % "0.64.8"
deleted

2024-05-21 09:04 UTC, MRBeresford commented on build.sbt
> +ThisBuild / scalaVersion := "2.13.12"
updated

2024-05-21 09:05 UTC, MRBeresford commented on project/AppDependencies.scala
> +    "org.wiremock"                %  "wiremock-standalone"      % "3.5.4",
deleted

2024-05-21 09:05 UTC, MRBeresford commented on project/AppDependencies.scala
>      "org.scalatest"               %% "scalatest"                % "3.2.18",
deleted

2024-05-21 09:31 UTC, frikit requested changes

2024-05-21 09:31 UTC, frikit commented on build.sbt
>  import uk.gov.hmrc.versioning.SbtGitVersioning.autoImport.majorVersion
delete this

2024-05-21 09:31 UTC, frikit commented on project/plugins.sbt
> -addSbtPlugin("io.github.irundaia"   % "sbt-sassify"             % "1.5.2")
add back sbt-sassify not sure it affects builds package

2024-05-21 09:46 UTC, frikit approved these changes

2024-05-21 09:51 UTC, merged